name: Create EKS Cluster

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4  # Versión de Terraform que deseas usar

      # Paso 3: Configurar las credenciales de AWS (usando los secretos de GitHub)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1  # Cambia la región según tus necesidades

      # Paso 4: Inicializar Terraform (esto configurará el backend S3)
      - name: Initialize Terraform
        run: terraform init

      # Paso 5: Ejecutar Terraform Plan y guardar el plan en un archivo
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Paso 6: Ejecutar Terraform Apply solo cuando el plan sea exitoso y en la rama main
      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Configure Kubernetes client
        uses: silverlyra/setup-aws-eks@v0.1
        with:
          cluster: example-eks-cluster

      - name: Install Helm
        uses: azure/setup-helm@v2

      - name: Add Helm Repositories
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts

      - name: Install Nginx
        run: |
          kubectl create namespace nginx-ingress-sample
          helm install my-nginx ingress-nginx/ingress-nginx \
              --namespace nginx-ingress-sample \
              --set controller.metrics.enabled=true \
              --set-string controller.metrics.service.annotations."prometheus\.io/port"="10254" \
              --set-string controller.metrics.service.annotations."prometheus\.io/scrape"="true"

      - name: Install Prometheus and Grafana
        run: |
          helm install prometheus prometheus-community/prometheus
          helm install grafana grafana/grafana

      - name: Deploy Application
        run: |
          kubectl apply -f ./deployment.yaml